#!/bin/bash
if [[ $# -lt 2 ]]; then
	echo "Usage:  git-remote-create repo_name ssh://server/~user/path/project_name.git [options to git-init]" 1>&2
	echo "For more, see http://github.com/aaronmcdaid/git-remote-create" 1>&2
	exit 1
fi
repo_name="$1"
url="$2"
shift
shift

if ! test ssh:// = ${url:0:6}; then
	echo "Error:  must be an ssh:// url" 1>&2
	exit 1
fi

without_proto="${url:6}"
server="$(echo "$without_proto" | cut -d/ -f1 | tr -d '\n')"
path_to_repo="$(echo "$without_proto" | cut -d/ -f2- | tr -d '\n')"
# echo "=$server="
# echo "=$path_to_repo="

echo "Logging into server: $server ..."
{ printf '%q' "$path_to_repo"; echo; } | ssh "$server" 'read -r path_to_repo && echo Creating Directory ... && the_path=$(eval echo ${path_to_repo}) && { test ! -d "$the_path" || { echo Already Exists! Exiting.; false; } } && mkdir -p "$the_path" && cd "$the_path" && git init && echo Created.'
if [[ 0 -ne "$?" ]]; then
	exit 1
fi

echo git remote add "$repo_name" "$url" "$@"
