#!/bin/bash
if [[ $# -lt 3 ]]; then
	echo "Usage:  git-remote-create repo_name server '~user/path/project_name.git' [options to git-init]" 1>&2
	echo "For more, see http://github.com/aaronmcdaid/git-remote-create" 1>&2
	exit 1
fi
repo_name="$1"
server="$2"
path_to_repo="$3"
shift
shift
shift # Three shifts so that the remaining args can be passed to git-init

if [[ / != "${path_to_repo:0:1}" && '~' != "${path_to_repo:0:1}" ]]; then
	echo "Error: The first character of the path should be either a / or a ~"
	exit 1
fi

# echo "=$server="
# echo "=$path_to_repo="

echo "Logging into server: $server ..."
 { printf '%q' "$path_to_repo"; echo; echo "$@"; } | ssh "$server" '{ read -r path_to_repo; read -r options_to_init; } && echo Creating Directory ... && the_path=$(eval echo ${path_to_repo}) && { test ! -d "$the_path" || { echo Already Exists! Exiting.; false; } } && mkdir -p "$the_path" && cd "$the_path" && git init $options_to_init && echo Created.'
if [[ 0 -ne "$?" ]]; then
	exit 1
fi

echo "Adding locally, and fetching ..."
exec git remote add -f "$repo_name" "ssh://$server/$path_to_repo"
